//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_MENU
    {
        public short MENU_ID { get; set; }
        public string MENU_TEXT { get; set; }
        public string TOOL_TIP { get; set; }
        public short ORDER_NO { get; set; }
        public string REF_URL { get; set; }
        public Nullable<short> PARENT_ID { get; set; }
        public bool HAS_CHILD { get; set; }
        public string ICON_IMAGES_LINK { get; set; }
        public byte MENU_TYPE_ID { get; set; }
    
        public virtual MENU_TYPE MENU_TYPE { get; set; }
    }
}
